config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'completed_points/index'
  resources :points
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks' 
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'completed_points', to: 'completed_points#create', as: 'completed_points'
  delete 'completed_points/:id', to: 'completed_points#destroy', as: 'delete_completed_point'
  get 'completeds/index'
  root 'completed_points#index'
end

app/models/completed_point.rb
class CompletedPoint < ApplicationRecord
  belongs_to :point
  belongs_to :user

  def self.completed_today(user)
    where(user_id: user).where(created_at: Date.today.beginning_of_day..Date.today.end_of_day)
  end 

  def start
    created_at
  end

  def as_json(options = {})
    options[:except] = :created_at
    options[:methods] = :start
    super(options)
  end

  def point_name
    point.name
  end
end

app/controllers/completed_points_controller.rb
class CompletedPointsController < ApplicationController
  before_action :set_params, only: [:destroy]
  
  def index
    @points = Point.where(user_id: current_user)
    @completed_points = CompletedPoint.completed_today(current_user)
    @new_completed_point = CompletedPoint.new
  end
  
  def create
    @points = CompletedPoint.new(completed_points_params)
    @points.point_status = true
    @points.user = current_user
    @points.save
    redirect_to root_path
  end

  def destroy
    @point.destroy
    redirect_to root_path
  end

  private

  def completed_points_params
   params.require(:completed_point).permit(:point_id)
  end

  def set_params
    @point = CompletedPoint.find(params[:id])
  end

end

app/helpers/completed_points_helper.rb
module CompletedPointsHelper
end

app/views/completed_points/_list.html.erb
<p id="notice"><%= notice %></p>
<table class="table table-bordered table-dark">
    <thead>
        <tr>
            <th scope="col" class="text-center">NOMBRE</th>
            <th scope="col" class="text-center">VALOR</th>
            <th scope="col" class="text-center">ESTADO</th>
            <th scope="col" class="text-center">ACCIONES</th>
            </th>
        </tr>
    </thead>
    <tbody>
        <% @completed_points.each do |completed_point| %>
        <tr>
            <td class="text-center"><%= completed_point.point.name %></td>
            <td class="text-center"><%= completed_point.point.point_value %></td>
            <td class="text-center"><%= completed_point.point_status ? 'Entregado' : 'No Entregado' %></td>
            <td class="text-center"><%= link_to  "Borrar", delete_completed_point_path(completed_point), class: 'btn btn-danger', method: :delete, data: {confirm: 'Estas Seguro'} %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/completed_points/index.html.erb
<%= form_with(model: @new_completed_point, local: true) do |form| %>
<table class="table table-striped table-hover ">
    <thead>
        <tr>
            <th class="text-center">TUS PUNTOS</th>
            <th class="text-center">ACCIONES</th>
        </tr>
    </thead>
    <tbody>
        <td class="text-center"><%= form.select(:point_id, options_for_select(@points.pluck(:name, :id))) %></td>
        <td class="text-center"><%= form.submit "Completar Punto", class: 'btn btn-light' %></td>
    </tbody>
</table>
<% end %>
<br>

<%= render  "list" %>