config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'completed_points/index'
  resources :points
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks' 
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'completed_points', to: 'completed_points#create', as: 'completed_points'
  delete 'completed_points/:id', to: 'completed_points#destroy', as: 'delete_completed_point'
  get 'completeds/index'
  root 'completed_points#index'
end

app/models/point.rb
class Point < ApplicationRecord
  validates_presence_of :name, on: :create, message: "no puede estar en blanco"
  validates_presence_of :name, on: :update, message: "no puede estar en blanco"
  validates :point_value, numericality: { only_integer: true }
  belongs_to :user
  has_many :completed_points
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_action :set_point, only: [:show, :edit, :update, :destroy]

  # GET /points
  # GET /points.json
  def index
    @points = Point.where(user_id: current_user)
  end

  # GET /points/1
  # GET /points/1.json
  def show
  end

  # GET /points/new
  def new
    @point = Point.new
  end

  # GET /points/1/edit
  def edit
  end

  # POST /points
  # POST /points.json
  def create
    @point = Point.new(point_params)
    @point.user = current_user

    respond_to do |format|
      if @point.save
        format.html { redirect_to @point, notice: 'Point was successfully created.' }
        format.json { render :show, status: :created, location: @point }
      else
        format.html { render :new }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /points/1
  # PATCH/PUT /points/1.json
  def update
    respond_to do |format|
      if @point.update(point_params)
        format.html { redirect_to @point, notice: 'Point was successfully updated.' }
        format.json { render :show, status: :ok, location: @point }
      else
        format.html { render :edit }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /points/1
  # DELETE /points/1.json
  def destroy
    @point.destroy
    respond_to do |format|
      format.html { redirect_to points_url, notice: 'Point was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_point
      @point = Point.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def point_params
      params.require(:point).permit(:name, :point_value, :user_id)
    end
end

app/helpers/points_helper.rb
module PointsHelper
end

app/views/points/_form.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-lg-3">
            <div class="card w-100 mt-5">
                <div class="card-body">
                    <%= form_with(model: point, local: true) do |form| %>
                    <% if point.errors.any? %>
                    <div id="error_explanation">
                        <h2><%= pluralize(point.errors.count, "error") %> prohibited this event from being saved:</h2>

                        <ul>
                            <% point.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                            <% end %>
                        </ul>
                    </div>
                    <% end %>
                    <div class="form-group">
                        <%= form.text_field :name, class: 'form-control', placeholder: 'Nombre del Punto' %>
                        <i class="iconinput fas fa-map-marker-alt"></i>
                    </div>
                    <div class="form-group">
                        <%= form.text_field :point_value, class: 'form-control', placeholder: 'Valor del Punto' %><i class="iconinput fas fa-dollar-sign"></i>
                    </div>
                    <div class="actions">
                        <%= form.submit "Crear Punto", class: 'col-md-12 btn btn-primary' %>
                        <% end %>
                    </div><br>
                    <div>
                        <%= link_to 'Atras', points_path, class: 'col-md-12 btn btn-primary' %>
                    </div>
                </div>
            </div>
        </div>
    </div>

app/views/points/edit.html.erb
<h1 class="text-center">Editar Punto</h1>

<%= render 'form', point: @point %>

app/views/points/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-md-20">
            <div class="card w-150 mt-5">
                <div class="card-body">
                    <h1 class="text-center">PUNTOS DE LOGISTICA</h1>

                    <table class="table table-striped table-hover ">
                        <thead>
                            <tr>
                                <th>NOMBRE</th>
                                <th>VALOR</th>
                                <th>USUARIO</th>
                                <th colspan="3"></th>
                            </tr>
                        </thead>

                        <tbody>
                            <% @points.each do |point| %>
                            <tr>
                                <td><%= point.name %></td>
                                <td><%= point.point_value %></td>
                                <td><%= point.user.name %></td>
                                <td><%= link_to 'Editar', edit_point_path(point), class: 'btn btn-light' %></td>
                                <td><%= link_to 'Destroy', point, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                    <center><%= link_to  "Nuevo Punto", new_point_path, class: 'col-md-5 btn btn-primary' %></center>
                </div>
            </div>
        </div>
    </div>

app/views/points/new.html.erb
<h1 class="text-center">Nuevo Punto</h1>
<%= render 'form', point: @point %>

app/views/points/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-lg-3">
            <div class="card w-100 mt-5">
                <div class="card-body">

                    <p>
                        <strong>Nombre:</strong>
                        <%= @point.name %>
                    </p>

                    <p>
                        <strong>Valor del Punto:</strong>
                        <%= @point.point_value %>
                    </p>

                    <p>
                        <strong>Usuario:</strong>
                        <%= @point.user.name %>
                    </p>

                    <%= link_to 'Editar', edit_point_path(@point), class: 'btn btn-info' %> |
                    <%= link_to 'Atras', points_path, class: 'btn btn-primary' %>

                </div>
            </div>
        </div>
    </div>