config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'completed_points/index'
  resources :points
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks' 
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'completed_points', to: 'completed_points#create', as: 'completed_points'
  delete 'completed_points/:id', to: 'completed_points#destroy', as: 'delete_completed_point'
  get 'completeds/index'
  root 'completed_points#index'
end

app/views/shared/_chart.html.erb
<%= javascript_include_tag "application", "chartkick" %>
<%= javascript_include_tag "//www.google.com/jsapi" %>

<% my_chart = CompletedPoint.group_by_day(:created_at).count %>
<%= column_chart my_chart %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-info fixed-top">
    <a class="navbar-brand">
        <% if user_signed_in? %>
        <%= image_tag user_avatar(current_user, 35), class: "rounded-circle" %> Operador: <%= current_user.name %>
        <% else %>
        <img src="https://cdn4.iconfinder.com/data/icons/aiga-symbol-signs/388/aiga_taxi-512.png" width="32" height="32" class="d-inline-block align-top" alt="">
        <h3 class="d-inline-block align-top">LOGISTICA</h3>
        <% end %>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item"><%= link_to "Inicio", root_path, class: "nav-link" %></li>
            <%= link_to 'Mis puntos', points_path, class: 'nav-link' %>
            <%= link_to 'Puntos Completados', completeds_index_path, class: 'nav-link' %>
            <%= link_to "Editar Perfil", edit_user_registration_path, class: "nav-link" %>
            <%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
            <% else %>
            <li class="nav-item"><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
        </ul>
        <% end %>
    </div>
    </div>
</nav>